export const countries = {
  'Russia': 'Россия',
  'Saudi Arabia': 'Саудовская Аравия',
  'Egypt': 'Египет',
  'Uruguay': 'Уругвай',
  'Portugal': 'Португалия',
  'Spain': 'Испания',
  'Morocco': 'Марокко',
  'Iran': 'Иран',
  'France': 'Франция',
  'Australia': 'Австралия',
  'Peru': 'Перу',
  'Denmark': 'Дания',
  'Argentina': 'Аргентина',
  'Iceland': 'Исландия',
  'Croatia': 'Хорватия',
  'Nigeria': 'Нигерия',
  'Brazil': 'Бразилия',
  'Switzerland': 'Швейцария',
  'Costa Rica': 'Коста-Рика',
  'Serbia': 'Сербия',
  'Germany': 'Германия',
  'Mexico': 'Мексика',
  'Sweden': 'Швеция',
  'South Korea': 'Южная Корея',
  'Belgium': 'Бельгия',
  'Panama': 'Панама',
  'Tunisia': 'Тунис',
  'England': 'Англия',
  'Poland': 'Польша',
  'Senegal': 'Сенегал',
  'Colombia': 'Колумбия',
  'Japan': 'Япония'
}
