export const localeCountries = {
  'Russia': 'Россия',
  'Saudi Arabia': 'Саудовская Аравия',
  'Egypt': 'Египет',
  'Uruguay': 'Уругвай',
  'Portugal': 'Португалия',
  'Spain': 'Испания',
  'Morocco': 'Марокко',
  'Iran': 'Иран',
  'France': 'Франция',
  'Australia': 'Австралия',
  'Peru': 'Перу',
  'Denmark': 'Дания',
  'Argentina': 'Аргентина',
  'Iceland': 'Исландия',
  'Croatia': 'Хорватия',
  'Nigeria': 'Нигерия',
  'Brazil': 'Бразилия',
  'Switzerland': 'Швейцария',
  'Costa Rica': 'Коста-Рика',
  'Serbia': 'Сербия',
  'Germany': 'Германия',
  'Mexico': 'Мексика',
  'Sweden': 'Швеция',
  'South Korea': 'Южная Корея',
  'Belgium': 'Бельгия',
  'Panama': 'Панама',
  'Tunisia': 'Тунис',
  'England': 'Англия',
  'Poland': 'Польша',
  'Senegal': 'Сенегал',
  'Colombia': 'Колумбия',
  'Japan': 'Япония'
}
export const localeCities = {
  'Moscow': 'Москва',
  'Saint Petersburg': 'Санкт-Петербург',
  'Kaliningrad': 'Калининград',
  'Kazan': 'Казань',
  'Nizhny Novgorod': 'Нижний Новгород',
  'Samara': 'Самара',
  'Volgograd': 'Волгоград',
  'Saransk': 'Саранск',
  'Rostov-on-Don': 'Ростов-на-Дону',
  'Sochi': 'Сочи',
  'Yekaterinburg': 'Екатеринбург'
}
export const localeStadiums = {
  'Luzhniki Stadium': 'Стадион Лужники',
  'Otkrytiye Arena': 'Стадион Спартак',
  'Krestovsky Stadium': 'Стадион Санкт-Петербург',
  'Kaliningrad Stadium': 'Стадион Калининград',
  'Kazan Arena': 'Казань Арена',
  'Nizhny Novgorod Stadium': 'Стадион Нижний Новгород',
  'Cosmos Arena': 'Самара Арена',
  'Volgograd Arena': 'Волгоград Арена',
  'Mordovia Arena': 'Мордовия Арена',
  'Rostov Arena': 'Ростов Арена',
  'Fisht Olympic Stadium': 'Стадион Фишт',
  'Central Stadium': 'Екатеринбург Арена'
}
